services:
  - type: web
    name: texan-rex-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: ta-connection-string-mongodb-atlas-ici
      - key: JWT_SECRET
        value: super-secret-jwt-key-production-123456789
      - key: PORT
        value: 10000

  - type: web  
    name: texan-rex-frontend
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: npx serve -s client/dist -p $PORT
    envVars:
      - key: NODE_ENV
        value: production